# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

hooch = Artist.create(name: "Pieter de Hooch", biography: "Pieter Hendricksz de Hooch (occasionally spelled de Hoogh) was baptized in the Reformed Church in Rotterdam on December 20, 1629. His father was a master bricklayer and his mother a midwife. His only recorded teacher was the land­scape painter Nicolaes Pietersz Berchem (Dutch, 1620 - 1683), with whom he studied in Haarlem along with fellow pupil Jacob Ochtervelt (1634–1682). The exact dates of this apprenticeship are not known. Berchem’s interest in landscape apparently had little effect on De Hooch, whose earliest paintings are almost all bar­rack-room scenes.

De Hooch is first recorded in Delft on August 5, 1652, when he and another painter, Hendrick van der Burch (1627–after 1666), witnessed the signing of a will. The following year he is documented as a painter and dienaar (servant or assistant) to a wealthy merchant named Justus de la Grange, a resident of both Delft and Leiden whose collection contained eleven of the artist’s paintings when it was inventoried in 1655. De Hooch witnessed a baptism in Leiden in 1653, but in 1654, when he married Jannetje van der Burch of Delft, he was living in Rotterdam. He and his wife, who was probably the sister of the painter Hendrick van der Burch, had seven children.

De Hooch entered the Delft guild in 1655 and is recorded as having paid dues in 1656 and 1657. He remained in that city until the end of the decade, but sometime between mid-1660 and April 1661 he set­tled in Amsterdam. Apart from a visit to Delft in 1663, he apparently remained in Amsterdam for the rest of his life. It was long believed that De Hooch died at the age of fifty-four while an inmate at the Amsterdam dolhuis (lunatic asylum).[1] However, that institution's records shows that the Pieter de Hooch who died in the asylum was the artist's son, also named Pieter.[2]
Between about 1655 and 1662, De Hooch’s work rose to the very highest level of achievement. Almost all of his paintings from these years depict interiors or courtyards containing just a few people, engaged either in domestic activities or in some restrained form of entertainment or merrymaking. The atmosphere in these works is characteristically calm, spacious, and airy, effects created through De Hooch’s masterly control of light, color, and com­plex perspectival construction. These are also all essential elements of the style of Johannes Vermeer (Dutch, 1632 - 1675), with whom he must have had contact.

By the end of the 1660s De Hooch’s work had lost much of its delicacy and finesse. His later compositions be­came grander and more contrived, and his color harmonies and light effects harsher. His last dated painting is from 1684. Although De Hooch had no known pupils, artists whose works have been confused with his include Hendrick van der Burch, Ludolf de Jongh (1616–1679), Pieter Janssens Elinga (1623–before 1682), and Esaias Boursse (1631–1672).")

diego= Artist.create(name: "Diego Velázquez", biography: "(baptized June 6, 1599, Sevilla, Spain—died August 6, 1660, Madrid), the most important Spanish painter of the 17th century, a giant of Western art. Velázquez is universally acknowledged as one of the world’s greatest artists. The naturalistic style in which he was trained provided a language for the expression of his remarkable power of observation in portraying both the living model and still life. Stimulated by the study of 16th-century Venetian painting, he developed from a master of faithful likeness and characterization into the creator of masterpieces of visual impression unique in his time. With brilliant diversity of brushstrokes and subtle harmonies of colour, he achieved effects of form and texture, space, light, and atmosphere that make him the chief forerunner of 19th-century French Impressionism.

The principal source of information about Velázquez’s early career is the treatise Arte de la pintura (“The Art of Painting”), published in 1649 by his master and father-in-law Francisco Pacheco, who is more important as a biographer and theoretician than as a painter. The first complete biography of Velázquez appeared in the third volume (El Parnaso español; “The Spanish Parnassus”) of El museo pictórico y escala óptica (“The Pictorial Museum and Optical Scale”), published in 1724 by the court painter and art scholar Antonio Palomino. This was based on biographical notes made by Velázquez’s pupil Juan de Alfaro, who was Palomino’s patron. The number of personal documents is very small, and official documentation relating to his paintings is relatively rare. Since he seldom signed or dated his works, their identification and chronology has often to be based on stylistic evidence alone. Though many copies of his portraits were evidently made in his studio by assistants, his own production was not large, and his surviving autograph works number fewer than 150. He is known to have worked slowly, and during his later years much of his time was occupied by his duties as a court official in Madrid.")

beale= Artist.create(name: "Mary Beale", biography: "Mary Beale (née Cradock; bapt. 26 March 1633 – bur. 8 October 1699) was amongst the most prolific and commercially successful British portrait painters of the late 17th century and, along with Joan Carlile (c.1606 -1679) and Susan Penelope Rosse (c.1655-1700) was part of a small band of female professional artists working in London. Beale became the main financial provider for her family through her professional work - a career she maintained from 1670/1 to the 1690s. Beale was also a writer, whose prose Discourse on Friendship of 1666 presents scholarly, uniquely female take on the subject. Her 1663 manuscript Observations on the materials and techniques employed 'in her painting of Apricots', though not printed, is the earliest known instructional text in English written by a female painter. Praised first as a 'virtuous' practitioner in 'Oyl Colours' by Sir William Sanderson in his 1658 book Graphice: Or The use of the Pen and Pensil; In the most Excellent Art of PAINTING, Beale’s work was later commended by court painter Sir Peter Lely and, soon after her death, by the author of 'An Essay towards an English-School', his account of the most noteworthy artists of her generation.")

hooch1= Artwork.create(title: "The Bedroom", artist_id: 1, image_url: "https://upload.wikimedia.org/wikipedia/commons/5/58/Pieter_de_Hooch_-", year: "1660", likes:0, description: "Pieter de Hooch excelled in the sensitive depiction of people going about their daily lives, be it inside their houses or in the sheltered environment of an urban courtyard. His masterly control of light, color, and complex perspectival construction can be compared to the work of Johannes Vermeer, his contemporary and colleague in Delft. Through his careful arrangement of the interior space in The Bedroom and his treatment of light, De Hooch infused this everyday scene with an extraordinary intimacy and warmth. Two light sources—the double windows on the left plus the open Dutch door and transom at the front of the house—illuminate the child who opens the door to the inner room. The doorway is flanked by rows of glazed Dutch tiles depicting popular children’s games. Based on the dress, the youngster could be either a girl or a boy. All small children wore skirts, regardless of gender, and the age at which a boy would change to wearing breeches was rather fluid. It is possible that De Hooch depicted his own family: his wife, Jannetje, and either his son, Peter, born in 1655, or his daughter, Anna, born in 1656. The painting’s traditional title of The Bedroom is somewhat misleading, for the box bed against the wall was part of a large multifunctional room. The mother, busy tending to the chamber pot and airing out the linens, prepares the room for its daytime uses. The harmonious character of De Hooch’s painting and its emphasis on the mother’s dual responsibility as nurturer of her child and caretaker of the home, embody the ideal of Dutch domestic felicity.")

hooch2= Artwork.create(title: "Woman and Child in a Courtyard", artist_id: 1, image_url: "https://upload.wikimedia.org/wikipedia/commons/5/50/Pieter_de_Hooch%2C_Woman_and_Child_in_a_Courtyard%2C_1658-1660%2C_NGA_1173.jpg", year: "1660", likes: 0, description:"Pieter de Hooch excelled in the sensitive depiction of people going about their daily lives, be it inside their houses or in the sheltered environment of an urban courtyard. His masterly control of light, color, and complex perspectival construction can be compared to the work of Johannes Vermeer, his contemporary and colleague in Delft. The old town wall of Delft forms the rear wall of a courtyard in which a maidservant, carrying a jug and a laundry basket, and a small child holding a birdcage make their way to the water pump. A woman and two men enjoy some red wine in the classically inspired arbor against the back wall. The same arbor, wall, and steps occur in two other De Hooch paintings, but the variations in composition confirm that the artist freely altered the architectural elements. It is unlikely that the courtyard scenes represent an actual location, but they are clearly based on views from the backyards of the houses on the west side of the Oude Gracht in Delft where De Hooch and his family are thought to have resided.")

diego1= Artwork.create(title: "Philip IV", artist_id: 2, image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Philip_IV_by_Velazquez.jpg", year: 1623, likes: 0, description: "We see King Philip IV of Spain (r. 1621-1665) when he was around twenty years old in an austere image filled with references to his status and responsibilities and to the reformist intentions with which he began his reign. The sword on whose hilt his left hand rests and the desk bearing a top allude to the administration of justice and the defense of his kingdoms. The Golden Fleece hanging at his waist symbolizes his lineage, while the paper in his right hand refers to his administrative duties. Even his suit is charged with meaning. It is much more sober than was customary in earlier royal portraits, lacking jewels and other adornments, and it is topped by a valona, a Walloon collar of the sort that replaced the more decorative and costly lechuguilla (ruff) in 1623. When this portrait was made, that plainer collar constituted the most important symbol of the desire for austerity, reform, work, and attention to public welfare that characterized the early reign of Philip IV, who sought to distance himself from the image of favoritism, caprice, and squandering associated with his predecessor, his father, King Philip III (r. 1598-1621).
During those early years of his reign, Philip IV frequently appeared in public with more costly and adorned clothing, but the official image created by Velázquez avoids these adornments and emphasizes one of the king`s most important activities as a ruler: his audiences. According to contemporary observers, he received his visitors on such occasions much as he is shown here: standing, leaning on a desk, and wearing the Golden Fleece. This play of references replete with political intent is brought out by the composition and the manner of painting. Velázquez places the king in a very stark space shaped with extremely subtle gradations of light and color and devoid of customary accessories such as curtains. Within this space, he locates the King very close to the viewer, wearing a suit painted with a prodigious variety of dark shades of color. The monarch`s posture is firm but relaxed, and the rendering of his face culminates a process of simplification that began with the portrait at the Meadows Museum; the result is an impassive expression directly related to the idea of royal majesty. With all those elements, Velázquez fashions an image of the king that differs considerably from any earlier one. The exceptional coherence between pictorial construction and narrative or symbolic elements places this among the summits of Spanish court portraiture, especially for its capacity to convey political ideals.")

diego2= Artwork.create(title:"The Adoration of the Magi", artist_id: 2, image_url: "https://upload.wikimedia.org/wikipedia/commons/7/73/Diego_Vel%C3%A1zquez_-_The_Adoration_of_the_Magi_-_WGA24359.jpg", year: "1619", likes: 0, description: "Painted in Seville in 1619, The Adoration of the Magi is the largest of Velázquez`s early works and, together with Saint Ildefonso receiving the Chasuble, the one with the most figures, making it one of the artist`s most ambitious compositions to date in his career. Both the above characteristics suggests that it was painted for a religious interior, very probably one associated with the Jesuits, given that the work`s first documented location was the novitiate of San Luis in Seville. After the expulsion of the Jesuits from Spain in 1767 the painting passed to the Escuela de Nobles Artes in Seville. This probable origin also tallies with the fact that Velázquez`s father-in-law Francisco Pacheco maintained good relations with the Jesuits. It also helps to explain the artist`s interest in lifelikeness and communicative immediacy, which reflects the pedagogical bent of a religious Order always concerned to exploit the devotional and didactic potential of language, while the figures are based on real models.
Serrera described this painting as a family portrait given that some figures have features of the artist`s own family. The king with the white beard on the far left is a portrait of Francisco Pacheco: the face is comparable to his self-portrait in the Last Judgment (Castres, Musée Goya) and to his portrait by Velázquez in the Museo del Prado. Similarly, the features of Saint Joseph and the kneeling king in the foreground are notably close to those of Saint John on Patmos (London, National Gallery) or to the supposed youthful self-portrait in the Prado, while the face of the youth in the background recalls the faces of some of the figures in the artist`s earlier genre scenes such as Old Woman frying Eggs. Finally, King Balthasar also seems to be based on a real person, while with regard to the Virgin and Child it has been pointed out on various occasions that Velázquez`s only daughter was born in 1619.
While it may seem surprising, the inclusion of portraits in an Adoration of the Magi is compatible with the traditions of that iconography. There are numerous examples in western art, some of them well known, such as Botticelli`s version. This practice can be related to the nature of this biblical episode, which affirms the universal character of the Good News. Velázquez echoes that tradition here, taking it to its furthest consequences by placing an unusual emphasis on the figures that are portraits. In narrative terms this is a simple image, lacking the complexity of other Sevillian works by the artist. The subject is immediately recognisable and is described in a direct manner so that the viewer easily identifies the episode and the key figures. The relationship established between the figures and the setting is markedly compatible with Velázquez`s compositional methods during his Sevillian period and also recalls that used for sculptural altarpieces. The bodies of the figures almost fill the entire composition and are located very close to the picture plane, giving them a pronounced expressivity and monumentality. Compositions of this type encouraged devotional concentration. Together with this unity the painting offers enormous variety with regard to the figure types, their actions and the chromatic range, which although it makes extensive use of ochres and blacks also includes extremely beautiful reds, whites and blues.
This combination of monumentality, beauty and expressive concentration, in addition to the skill with which Velázquez represented the individual expressions on the faces, makes The Adoration of the Magi one of the masterpieces of the artist`s early period. It is in many respects comparable to The Waterseller of Seville, in which the figures also fill the pictorial surface while the artist makes comparable use of the spatial planes (Text from Portús, J.: Velázquez, Kunsthistorisches Museum, Wien, 2014, p. 291).")

beale1= Artwork.create(title:"Portrait of a Young Girl", artist_id: 3, image_url:"https://upload.wikimedia.org/wikipedia/commons/9/9e/Mary_Beale_-_Portrait_of_a_Young_Girl_-_Google_Art_Project.jpg", year: "1681", likes: 0, description: "In 1681, a year in which a great deal is known about Mary Beale due to the survival of her husband's notebook (Heinz Archive, National Portrait Gallery), it is recorded that she undertook several paintings for the purpose of 'study & improvement'. This portrait study is very possibly an example of such a work.

In the notebook, really an annotated almanac, Charles Beale (1631-1705) lists his wife's activities for each day, detailing her commissioned portraits as well as the experimental studies. For the latter, he identifies the sitters and, in most cases, their poses and tracks the progress of each work from one sitting to the next, paying particular attention if a novel technique had been used. It becomes clear that Mary Beale's purpose in carrying out the studies, as well as to develop her skill, was to test out, in conjunction with her husband, various painting methods. Charles Beale's interest in the technical aspect of painting is known to date back to at least 1647, when he began a journal entitled Experimental Secrets found out in the way of Painting (Glasgow University Library). This, as well as his notebooks of 1677 (Bodleian Library, Oxford) and 1681, are full of notes relating to his trials in manufacturing expensive pigments, his experiments in priming canvases and his efforts to perfect procedures such as the quick-drying of paint layers. It was this aspect of the painting studio that Charles oversaw, a business which was a collaborative partnership between husband and wife. Together they sought to improve the studio's efficiency, through perfecting procedures that would produce good results at a lower cost.

The portraits executed for study were painted on a variety of supports - fine canvas, sacking, onion bag and bed ticking. Mary's models, apart from herself and her husband, were her son Charles, Kate Trioche (a studio assistant), Alice Woodforde (her godchild) and Katy Sandys, who were painted in a variety of informal poses. It is not possible to match this study with a particular reference in the 1681 notebook, although it is close to the description of Kate Trioche's portrait painted on 17 May, 'side face fint. up at once upon a hungry, fine Canvis, of the least Size but one with a hand in it', and also to a similar one of Alice Woodforde done on 27 May. The canvas used here is not 'fine' but it does seem to have been 'painted up at once', in other words in one session rather than the average four. This quick process was one that Mary and Charles were attempting to master. It could result in colours appearing muddy and opaque, as has happened to some extent in this work. Nevertheless, its immediacy and informality makes it, arguably, one of Mary Beale's most appealing works.")

beale2= Artwork.create(title:"Mary Beale", artist_id: 3, image_url: "https://upload.wikimedia.org/wikipedia/commons/5/59/Mary_Beale_-_Zelfportret_van_Mary_Beale_%281633-1699%29_-_NPG_1687_-_National_Portrait_Gallery.jpg", year:"1666", likes: 0, description: "Mary Beale shows herself as artist and mother; her palette hangs on the wall and her right hand supports a small canvas showing unfinished portraits of her two sons, Bartholomew (1656-1705) and Charles (1660-1714?). Their apparent ages allow the canvas to be dated c.1666, when the Beales were living at Albrook in Hampshire. Plausibly considered to be the companion to Mary Beale’s portrait of her husband Charles (of the same unusual canvas size), now with the St Edmondsbury Borough Council (see Charles Beale c.1666). Together the two canvases show the complete young family.")
