# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

hooch = Artist.create(name: "Pieter de Hooch", biography: "Pieter Hendricksz de Hooch (occasionally spelled de Hoogh) was baptized in the Reformed Church in Rotterdam on December 20, 1629. His father was a master bricklayer and his mother a midwife. His only recorded teacher was the land­scape painter Nicolaes Pietersz Berchem (Dutch, 1620 - 1683), with whom he studied in Haarlem along with fellow pupil Jacob Ochtervelt (1634–1682). The exact dates of this apprenticeship are not known. Berchem’s interest in landscape apparently had little effect on De Hooch, whose earliest paintings are almost all bar­rack-room scenes.

De Hooch is first recorded in Delft on August 5, 1652, when he and another painter, Hendrick van der Burch (1627–after 1666), witnessed the signing of a will. The following year he is documented as a painter and dienaar (servant or assistant) to a wealthy merchant named Justus de la Grange, a resident of both Delft and Leiden whose collection contained eleven of the artist’s paintings when it was inventoried in 1655. De Hooch witnessed a baptism in Leiden in 1653, but in 1654, when he married Jannetje van der Burch of Delft, he was living in Rotterdam. He and his wife, who was probably the sister of the painter Hendrick van der Burch, had seven children.

De Hooch entered the Delft guild in 1655 and is recorded as having paid dues in 1656 and 1657. He remained in that city until the end of the decade, but sometime between mid-1660 and April 1661 he set­tled in Amsterdam. Apart from a visit to Delft in 1663, he apparently remained in Amsterdam for the rest of his life. It was long believed that De Hooch died at the age of fifty-four while an inmate at the Amsterdam dolhuis (lunatic asylum).[1] However, that institution's records shows that the Pieter de Hooch who died in the asylum was the artist's son, also named Pieter.[2]
Between about 1655 and 1662, De Hooch’s work rose to the very highest level of achievement. Almost all of his paintings from these years depict interiors or courtyards containing just a few people, engaged either in domestic activities or in some restrained form of entertainment or merrymaking. The atmosphere in these works is characteristically calm, spacious, and airy, effects created through De Hooch’s masterly control of light, color, and com­plex perspectival construction. These are also all essential elements of the style of Johannes Vermeer (Dutch, 1632 - 1675), with whom he must have had contact.

By the end of the 1660s De Hooch’s work had lost much of its delicacy and finesse. His later compositions be­came grander and more contrived, and his color harmonies and light effects harsher. His last dated painting is from 1684. Although De Hooch had no known pupils, artists whose works have been confused with his include Hendrick van der Burch, Ludolf de Jongh (1616–1679), Pieter Janssens Elinga (1623–before 1682), and Esaias Boursse (1631–1672).")

diego= Artist.create(name: "Diego Velázquez", biography: "(baptized June 6, 1599, Sevilla, Spain—died August 6, 1660, Madrid), the most important Spanish painter of the 17th century, a giant of Western art. Velázquez is universally acknowledged as one of the world’s greatest artists. The naturalistic style in which he was trained provided a language for the expression of his remarkable power of observation in portraying both the living model and still life. Stimulated by the study of 16th-century Venetian painting, he developed from a master of faithful likeness and characterization into the creator of masterpieces of visual impression unique in his time. With brilliant diversity of brushstrokes and subtle harmonies of colour, he achieved effects of form and texture, space, light, and atmosphere that make him the chief forerunner of 19th-century French Impressionism.

The principal source of information about Velázquez’s early career is the treatise Arte de la pintura (“The Art of Painting”), published in 1649 by his master and father-in-law Francisco Pacheco, who is more important as a biographer and theoretician than as a painter. The first complete biography of Velázquez appeared in the third volume (El Parnaso español; “The Spanish Parnassus”) of El museo pictórico y escala óptica (“The Pictorial Museum and Optical Scale”), published in 1724 by the court painter and art scholar Antonio Palomino. This was based on biographical notes made by Velázquez’s pupil Juan de Alfaro, who was Palomino’s patron. The number of personal documents is very small, and official documentation relating to his paintings is relatively rare. Since he seldom signed or dated his works, their identification and chronology has often to be based on stylistic evidence alone. Though many copies of his portraits were evidently made in his studio by assistants, his own production was not large, and his surviving autograph works number fewer than 150. He is known to have worked slowly, and during his later years much of his time was occupied by his duties as a court official in Madrid.")

beale= Artist.create(name: "Mary Beale", biography: "Mary Beale (née Cradock; bapt. 26 March 1633 – bur. 8 October 1699) was amongst the most prolific and commercially successful British portrait painters of the late 17th century and, along with Joan Carlile (c.1606 -1679) and Susan Penelope Rosse (c.1655-1700) was part of a small band of female professional artists working in London. Beale became the main financial provider for her family through her professional work - a career she maintained from 1670/1 to the 1690s. Beale was also a writer, whose prose Discourse on Friendship of 1666 presents scholarly, uniquely female take on the subject. Her 1663 manuscript Observations on the materials and techniques employed 'in her painting of Apricots', though not printed, is the earliest known instructional text in English written by a female painter. Praised first as a 'virtuous' practitioner in 'Oyl Colours' by Sir William Sanderson in his 1658 book Graphice: Or The use of the Pen and Pensil; In the most Excellent Art of PAINTING, Beale’s work was later commended by court painter Sir Peter Lely and, soon after her death, by the author of 'An Essay towards an English-School', his account of the most noteworthy artists of her generation.")
